# Generated by Django 4.2.6 on 2023-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('W', 'Wrench'), ('B', 'Bolts'), ('BR', 'Brakes')], default='W', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('W', 'Wrench'), ('B', 'Bolts'), ('BR', 'Brakes')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
